spring.application.name=Linkdlyst

# base path of the application
server.servlet.context-path=/api

# Disable AWS Secrets Manager lookup during tests
# spring.cloud.aws.secretsmanager.enabled=false

# Get secrets from AWS Secrets Manager with store name prod/linkdlyst 
# AWS Secrets Manager
spring.config.import=aws-secretsmanager:prod/linkdlyst


# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Minimum number of idle connections maintained by HikariCP in the pool
spring.datasource.hikari.minimum-idle=5
# Maximum number of connections (both idle and in-use) in the pool
spring.datasource.hikari.maximum-pool-size=20

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#JWT Secrets
#time in milliseconds i.e 15 minutes = 900000 milliseconds
#secret key must be minimum of 32 bytes
jwt.secret=${JWT_SECRET}
jwt-access-token-expiration=${JWT_ACCESS_TOKEN_EXPIRATION}
jwt-refresh-token-expiration=${JWT_REFRESH_TOKEN_EXPIRATION}

#Redis Configuration
# Redis
spring.data.redis.url=${REDIS_URL}

#SendGrid Credentials 
sendgrid.api-key=${SENDGRID_APIKEY}
sendgrid.from-email=${SENDGRID_EMAIL}
sendgrid.from-name=${SENDGRID_FROM_NAME}